# Generated by Django 5.2.17 on 2026-10-01 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_role_profiles(apps, schema_editor):
    User = apps.get_model('api', 'User')
    StudentProfile = apps.get_model('api', 'StudentProfile')
    TeacherProfile = apps.get_model('api', 'TeacherProfile')
    database = schema_editor.connection.alias

    StudentProfile.objects.using(database).bulk_create([
        StudentProfile(user_id=user_id)
        for user_id in User.objects.using(database).filter(role='student').values_list('id', flat=True)
    ], ignore_conflicts=True)
    TeacherProfile.objects.using(database).bulk_create([
        TeacherProfile(user_id=user_id)
        for user_id in User.objects.using(database).filter(role='teacher').values_list('id', flat=True)
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_existing_role_profiles, migrations.RunPython.noop),
    ]
