# Generated by Django 5.2.17 on 2026-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
