# Generated by Django 5.2.17 on 2026-10-01 12:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_assignmentsubmission_response_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.assignment_upload_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('quiz', 'Тест с одним правильным ответом'), ('multiple_choice', 'Тест с несколькими правильными ответами'), ('file_upload', 'Загрузка файла'), ('short_answer', 'Краткий ответ')], default='text', max_length=20),
        ),
    ]
