# Generated by Django 5.2.17 on 2026-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_assignmentsubmission_original_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assignment',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(default=128),
        ),
        migrations.AddField(
            model_name='assignment',
            name='programming_language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('quiz', 'Тест с одним правильным ответом'), ('multiple_choice', 'Тест с несколькими правильными ответами'), ('file_upload', 'Загрузка файла'), ('short_answer', 'Краткий ответ'), ('code', 'Решение кодом')], default='text', max_length=20),
        ),
    ]
