# Generated by Django 5.2.17 on 2026-10-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_assignment_hints_assignment_memory_limit_mb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api.assignment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
