# Generated by Django 5.2.17 on 2026-10-05 05:11

from django.db import migrations, models


def copy_legacy_code_submissions(apps, schema_editor):
    Submission = apps.get_model('api', 'AssignmentSubmission')
    Assignment = apps.get_model('api', 'Assignment')
    submissions_to_update = []
    for submission in Submission.objects.filter(
        assignment__assignment_type='code',
    ).select_related('assignment').iterator():
        changed = False
        if not submission.source_code and submission.answer_text:
            submission.source_code = submission.answer_text
            changed = True
        if not submission.language:
            submission.language = submission.assignment.programming_language
            changed = True
        if changed:
            submissions_to_update.append(submission)
    Submission.objects.bulk_update(
        submissions_to_update,
        ['source_code', 'language'],
        batch_size=500,
    )
    Assignment.objects.filter(
        assignment_type='code',
        memory_limit_mb__lt=64,
    ).update(memory_limit_mb=64)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='error_message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='execution_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='memory_used_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='source_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(copy_legacy_code_submissions, migrations.RunPython.noop),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='tests_passed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='tests_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('passed', 'Успешно'), ('failed', 'Не прошло проверки'), ('timeout', 'Таймаут'), ('runtime_error', 'Ошибка выполнения'), ('compile_error', 'Ошибка компиляции'), ('system_error', 'Системная ошибка'), ('submitted', 'Отправлено'), ('graded', 'Проверено')], default='submitted', max_length=20),
        ),
    ]
