# Generated by Django 5.2.17 on 2026-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_assignmentsubmission_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='runner_task_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
